"""
FIO job file generation from a KV I/O trace.

Maps the observed LMCache disk workload onto FIO's model:

- Each KV chunk is one file of near-constant size (the dominant write size);
  whole-file sequential writes on create, whole-file reads on cache hit.
- Observed writer/reader parallelism becomes numjobs — multiple concurrent
  writers to one device is what produces interleaved chunk data on media,
  the behavior this workload exists to reproduce.
- Eviction (delete + new create) is approximated by capping the file set at
  the observed steady-state count so writes recycle files. FIO cannot
  delete files mid-run; overwrite-in-place is the closest native model and
  keeps the device at steady-state occupancy. The delete rate is documented
  in the generated file for tools that can model it (or for a wrapper
  script that unlinks files out-of-band).
- O_DIRECT is carried over from the backend's observed configuration.

The generated file is deliberately verbose: every parameter cites the trace
measurement it came from, so it can be reviewed and hand-tuned.
"""

from __future__ import annotations

from kvbench.trace.analyze import TraceSummary


def _fmt_bytes(n: int | None) -> str:
    if not n:
        return "0"
    for unit, factor in (("G", 1024**3), ("M", 1024**2), ("K", 1024)):
        if n % factor == 0:
            return f"{n // factor}{unit}"
        if n >= factor * 4:
            return f"{n / factor:.1f}{unit}"
    return str(n)


def generate_fio_job(
    summary: TraceSummary,
    directory: str = "/mnt/kvcache",
    runtime_s: int = 300,
    paced: bool = False,
) -> str:
    """Generate an FIO job file from a trace summary.

    Args:
        summary: Trace summary (from kvbench.trace.analyze.summarize).
        directory: Target directory for the FIO file set.
        runtime_s: Runtime for the time-based jobs.
        paced: Cap each job at the observed throughput instead of running
            at full device speed (reproduce the workload's intensity, not
            just its shape).

    Returns:
        FIO job file content.

    Raises:
        ValueError: If the trace contains no write I/O to model.
    """
    write = summary.io_write
    read = summary.io_read

    chunk_bytes = write.dominant_size
    if not chunk_bytes:
        raise ValueError(
            "Trace contains no physical write events for backend "
            f"{summary.backend!r}; cannot derive an FIO workload. "
            "Run a workload (or warmup) with tracing enabled first."
        )

    write_jobs = max(1, write.max_concurrency)
    read_jobs = max(1, read.max_concurrency) if read.count else 0

    # File set: steady-state occupancy if eviction was active, else all
    # files ever written. Split across write jobs (FIO filenames are
    # per-job unless shared).
    total_files = max(summary.steady_state_files, write_jobs, 16)
    files_per_write_job = max(1, total_files // write_jobs)
    files_per_read_job = max(1, total_files // read_jobs) if read_jobs else 0

    direct = 1 if summary.use_odirect else 0
    size_str = _fmt_bytes(chunk_bytes)

    read_write_ratio = (
        f"{read.total_bytes / write.total_bytes:.2f}" if write.total_bytes else "n/a"
    )
    remove_rate = (
        f"{summary.logical_remove.count / write.span_s:.2f}/s"
        if write.span_s > 0 and summary.logical_remove.count
        else "none observed"
    )

    lines = [
        "; FIO job file generated by `kvbench trace2fio`",
        f"; Source backend: {summary.backend}",
        ";",
        "; Trace measurements this file is derived from:",
        f";   chunk file size (dominant write size): {chunk_bytes} bytes",
        f";   write ops: {write.count} ({write.total_bytes} bytes, "
        f"{write.bytes_per_sec / 1e6:.1f} MB/s over {write.span_s:.1f}s)",
        f";   read ops:  {read.count} ({read.total_bytes} bytes, "
        f"{read.bytes_per_sec / 1e6:.1f} MB/s over {read.span_s:.1f}s)",
        f";   read/write byte ratio: {read_write_ratio}",
        f";   max concurrent writes: {write.max_concurrency} "
        f"(distinct writer threads: {len(write.threads)})",
        f";   max concurrent reads:  {read.max_concurrency} "
        f"(distinct reader threads: {len(read.threads)})",
        f";   median write latency: {write.median_dur_ms or 0:.2f} ms; "
        f"median read latency: {read.median_dur_ms or 0:.2f} ms",
        f";   evictions (file deletes): {summary.logical_remove.count} ({remove_rate})",
        f";   steady-state file count: {summary.steady_state_files} "
        f"(writes {write.count} - removes {summary.logical_remove.count})",
        f";   O_DIRECT: {'yes' if summary.use_odirect else 'no'}",
        ";",
        "; Modeling notes:",
        ";   - One file per KV chunk; whole-file sequential write on store,",
        ";     whole-file read on cache hit (bs = filesize = chunk size).",
        ";   - numjobs reproduces the observed operation-level parallelism;",
        ";     concurrent writers interleave chunk data on the device.",
        ";   - Eviction churn is approximated by recycling a fixed file set",
        ";     (nrfiles at steady-state count, overwrite on wrap). FIO cannot",
        ";     unlink mid-run; if delete+recreate allocation behavior matters",
        ";     to the system under test, unlink files out-of-band at the",
        ";     eviction rate noted above.",
        "",
        "[global]",
        f"directory={directory}",
        "ioengine=psync",
        f"direct={direct}",
        "thread",
        "group_reporting",
        f"runtime={runtime_s}",
        "time_based",
        f"bs={size_str}",
        f"filesize={size_str}",
        "file_service_type=random",
        "create_on_open=1",
        "allow_file_create=1",
        "",
        "[kv-chunk-write]",
        f"; {write_jobs} concurrent writer(s), whole-file writes of {size_str} chunks",
        "rw=write",
        f"numjobs={write_jobs}",
        f"nrfiles={files_per_write_job}",
        "fsync_on_close=0",
    ]
    if paced and write.bytes_per_sec > 0:
        lines.append(f"rate={int(write.bytes_per_sec / write_jobs)}")

    if read_jobs:
        lines += [
            "",
            "[kv-chunk-read]",
            f"; {read_jobs} concurrent reader(s), whole-file reads of {size_str} chunks",
            "rw=randread",
            f"numjobs={read_jobs}",
            f"nrfiles={files_per_read_job}",
            "; readers touch the same working set the writers maintain",
        ]
        if paced and read.bytes_per_sec > 0:
            lines.append(f"rate={int(read.bytes_per_sec / read_jobs)}")

    lines.append("")
    return "\n".join(lines)
